import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import I18nProvider from "./i18n-provider";
import NavbarTop from "@/components/nav/navTop";
import NavbarBottom from "@/components/nav/navBottom";
import Hero from "@/components/page/Hero";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <I18nProvider>
          <NavbarTop/>
          <Hero/>
           <main >
            {children}
          </main>
          <NavbarBottom/>
        </I18nProvider>
      </body>
    </html>
  );
}
